### ISSUE TITLE
Novas alterações no projeto

### ISSUE THREAD

**Issue by willyandan** [willyandan/prototype-me.js#4]
# Prototype me
Algumas novas funcionalidades serão adicionadas para que seja possível prototipar uma API inteira:
## TODO List
- [ ] Criar um template para api
- [ ] Alterar package.json gerado
- [ ] Integrar template com o prototype-me
- [ ] Add LICENSE
- [ ] Alterar README.MD
 

## Criando template de API
- [x] scripts/server.js
- [x] scripts/client.js
- [x] server/
- [x] server/src/controllers/
- [x] server/src/models/
- [x] server/src/routers/
- [x] server/src/validators/
- [x] server/app.js
- [x] client/
- [x] credentials/env.base.json
- [x] credentials/env.json
- [x] public/
- [x] tests/
- [ ] README.MD
- [x] package.json
- [x] .gitignore

## Integrando o template ao projeto
- [ ] Passando template para o diretório do cliente
- [ ] Colocando rotas dentro do diretório
- [ ] executando npm install dentro do cliente

**Comment by anmarco** [comment]
👌👌👌👌 🔝 🔝 🔝 🔝 🔝

**Comment by willyandan** [comment]
👌
